export const achievements = [
    {
        id: 0,
        titleFr: "C'est mieux à deux",
        titleEn: "It's better with two",
        descriptionFr: "Ajouter un ami",
        descriptionEn: "Add a friend",
        condition: false,
    },
    {
        id: 1,
        titleFr: "Plus on est de fous...",
        titleEn: "The more the merrier...",
        descriptionFr: "Ajouter 5 amis",
        descriptionEn: "Add 5 friends",
        condition: false,
    },
    {
        id: 2,
        titleFr: "J'ai le bras long",
        titleEn: "I have a long arm",
        descriptionFr: "Ajouter 50 amis",
        descriptionEn: "Add 50 friends",
        condition: false,
    },
    {
        id: 3,
        titleFr: "Compétiteur",
        titleEn: "Competitor",
        descriptionFr: "Être premier parmi ses amis (XP) 10 jours de suite",
        descriptionEn: "Be first among friends (XP) 10 days in a row",
        condition: false,
    },
    {
        id: 4,
        titleFr: "Dès le matin !",
        titleEn: "First thing in the morning",
        descriptionFr: "Etudier entre 5h et 8h du matin",
        descriptionEn: "Study between 5am and 8am",
        condition: false,
    },
    {
        id: 5,
        titleFr: "Toute la nuit",
        titleEn: "All night long",
        descriptionFr: "Etudier entre miniut et 3 heures",
        descriptionEn: "Study between midnight and 3am",
        condition: false,
    },
    {
        id: 6,
        titleFr: "Semaine enflammée",
        titleEn: "Hot week",
        descriptionFr: "Etudier tous les jours pendant une semaine",
        descriptionEn: "Study every day for a week",
        condition: false,
    },
    {
        id: 7,
        titleFr: "Mois studieux",
        titleEn: "Studious month",
        descriptionFr: "Etudier tous les jours pendant un mois",
        descriptionEn: "Study every day for a month",
        condition: false,
    },
    {
        id: 8,
        titleFr: "Nouvelle ère",
        titleEn: "A new era",
        descriptionFr: "Etudier tous les jours pendant un an",
        descriptionEn: "Study every day for a year",
        condition: false,
    },
    {
        id: 9,
        titleFr: "Le savoir est une arme",
        titleEn: "Knowledge is a weapon",
        descriptionFr: "Etudier tous les jours pendant 1000 jours",
        descriptionEn: "Study every day for 1000 days",
        condition: false,
    },
    {
        id: 10,
        titleFr: "Multi-taches",
        titleEn: "Multi-tasking",
        descriptionFr: "Etudier 3 cours en meme temps",
        descriptionEn: "Study 3 courses at the same time",
        condition: false,
    },
    {
        id: 11,
        titleFr: "Curieux",
        titleEn: "Curious",
        descriptionFr: "Etudier 5 cours en meme temps",
        descriptionEn: "Study 5 courses at the same time",
        condition: false,
    },
    {
        id: 12,
        titleFr: "Emilien",
        titleEn: "Emilien",
        descriptionFr: "Etudier 10 cours en meme temps",
        descriptionEn: "Study 10 courses at the same time",
        condition: false,
    },
    {
        id: 13,
        titleFr: "Petite pause ?",
        titleEn: "A short break?",
        descriptionFr: "Revenir après 7 jours d'inactivité",
        descriptionEn: "Come back after 7 days of inactivity",
        condition: false,
    },
    {
        id: 14,
        titleFr: "Ca fait longtemps",
        titleEn: "It's been a while",
        descriptionFr: "Revenir après un mois d'inactivité",
        descriptionEn: "Come back after a month's inactivity",
        condition: false,
    },
    {
        id: 15,
        titleFr: "Nouveau départ",
        titleEn: "A fresh start",
        descriptionFr: "Revenir après un an d'inactivité",
        descriptionEn: "Come back after a year's inactivity",
        condition: false,
    },
    {
        id: 16,
        titleFr: "Cet affreux cauchemard est terminé",
        titleEn: "This awful nightmare is over",
        descriptionFr: "Connaitre toutes les cartes d'un cours",
        descriptionEn: "See all the cards in a course",
        condition: false,
    },
    {
        id: 17,
        titleFr: "Créateur",
        titleEn: "Creator",
        descriptionFr: "Créer un cours",
        descriptionEn: "Create a course",
        condition: false,
    },
    {
        id: 18,
        titleFr: "Petika et repetika sont dans un bateau",
        titleEn: "Petika and repetika are in a boat",
        descriptionFr: "Installer l'application",
        descriptionEn: "Install the application",
        condition: false,
    },
    {
        id: 19,
        titleFr: "Bonne résolution",
        titleEn: "Good resolution",
        descriptionFr: "Réviser le premier janvier",
        descriptionEn: "Revise on the first of January",
        condition: false,
    },
    {
        id: 20,
        titleFr: "All I want for Christmas is you",
        titleEn: "All I want for Christmas is you",
        descriptionFr: "Réviser le jour de Noël",
        descriptionEn: "Revise on Christmas Day",
        condition: false,
    },
    {
        id: 21,
        titleFr: "El professor",
        titleEn: "El professor",
        descriptionFr: "Avoir créé 5 cours",
        descriptionEn: "Have created 5 courses",
        condition: false,
    },
    {
        id: 22,
        titleFr: "L'étudiant",
        titleEn: "The student",
        descriptionFr: "Avoir importé 3 cours dans l'application",
        descriptionEn: "Imported 3 courses into the application",
        condition: false,
    },
    {
        id: 23,
        titleFr: "Fouineur",
        titleEn: "Snoop",
        descriptionFr: "Avoir cliqué 27 fois (d'affilée) sur le nom de la version de l'app",
        descriptionEn: "Clicked 27 times (in a row) on the app version name",
        condition: false,
    },
    {
        id: 24,
        titleFr: "Développeur",
        titleEn: "Developer",
        descriptionFr: 'Avoir nommé un cours "TEST_DEV_PANORAMA"',
        descriptionEn: 'Named a course "TEST_DEV_PANORAMA"',
        condition: false,
    },
    {
        id: 25,
        titleFr: "Omniscient",
        titleEn: "Omniscient",
        descriptionFr: 'S\'appeler "Damien Louet"',
        descriptionEn: 'Your name is "Damien Louet"',
        condition: false,
    }
];
