apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service
          image: "{{ .Values.image.registry }}/main-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "{{ .Values.global.django.allowedHosts }}"
            - name: MONGO_URI
              value: "mongodb://{{ .Values.global.mongo.host }}:{{ .Values.global.mongo.port }}/{{ .Values.global.mongo.dbName }}"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
