apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nginx:1.25
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config
          configMap:
            name: gateway-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
