apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ .Values.global.mongo.host }}   # must match Service name
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongo.image }}
          securityContext:
            allowPrivilegeEscalation: false # Here mainly to silence semgrep, doens't make much sense since the container is already root
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.global.mongo.dbName | quote }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          # Optional health checks (similar to docker-compose)
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}
