{{- if .Values.mongoSeed.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "repetika.fullname" . }}-mongo-seed
data:
{{- $files := .Files.Glob "files/mongo-seed/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |
{{ $file | toString | indent 4 }}
{{- end }}
{{- end }}
