{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["prometheus:9090"]

      # Django microservices
      - job_name: "repetika-django"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "authentification-service:8000"
              - "cours-service:8000"
              - "decks-service:8000"
              - "planning-service:8000"
              - "session-service:8000"
              - "quiz-service:8000"
              - "main-service:8000"

      - job_name: "cadvisor"
        static_configs:
          - targets: ["cadvisor:8070"]

      - job_name: "node-exporter"
        static_configs:
          - targets: ["node-exporter:9100"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          securityContext:
            allowPrivilegeEscalation: false
          image: {{ .Values.monitoring.prometheus.image }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          emptyDir: {}   # TODO: Add PVC later for persistence

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 32001

{{- end }}
