# charts/repetika/values.yaml

global:
  namespace: repetika

  app:
    secretKey: "change_me_dev_secret" # TODO: Change in prod

  django:
    allowedHosts: "*"

  mongo:
    host: mongodb        # K8s Service name
    port: 27017
    dbName: repetika     # Matches default DB name used by Repetika

  postgres:
    host: postgres
    port: 5432
    db: authdb
    user: authuser
    password: authpass

image:
  registry: repetika
  tag: "local"
  pullPolicy: IfNotPresent

backend:
  services:
    main:
      name: main-service
      containerPort: 8000
    decks:
      name: decks-service
      containerPort: 8000
    cours:
      name: cours-service
      containerPort: 8000
    planning:
      name: planning-service
      containerPort: 8000
    session:
      name: session-service
      containerPort: 8000
    quiz:
      name: quiz-service
      containerPort: 8000
    auth:
      name: authentification-service
      containerPort: 8000

mongo:
  enabled: true
  image: mongo:7
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi

postgres:
  enabled: true
  image: postgres:16
  persistence:
    enabled: true
    size: 1Gi
