# Generated by Django 5.2 on 2025-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="685454a7e70768c6ffdfe6c6",
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
