# Generated by Django 5.2 on 2025-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentification", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="685455d13955cd1a7be9baf9",
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
