apiVersion: apps/v1
kind: Deployment
metadata:
  name: TimeService-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: TimeService
  template:
    metadata:
      labels:
        app: TimeService
    spec:
      containers:
      - name: TimeService
        image: myregistry.com/TimeService:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: core.settings
        - name: DJANGO_DEBUG
          value: "0"
        - name: DB_HOST
          value: postgres.default.svc.cluster.local
        envFrom:
        - secretRef:
            name: django-secrets
        volumeMounts:
        - name: settings-volume
          mountPath: /app/core/core/settings.py
          subPath: settings.py
      volumes:
      - name: settings-volume
        configMap:
          name: django-settings

