# Generated by Django 4.2.21 on 2025-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="685037b32115bcf3b46e2ca1",
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
